# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AssetsBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, metadata: object=None, content: str=None):  # noqa: E501
        """AssetsBody - a model defined in Swagger

        :param metadata: The metadata of this AssetsBody.  # noqa: E501
        :type metadata: object
        :param content: The content of this AssetsBody.  # noqa: E501
        :type content: str
        """
        self.swagger_types = {
            'metadata': object,
            'content': str
        }

        self.attribute_map = {
            'metadata': 'metadata',
            'content': 'content'
        }
        self._metadata = metadata
        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'AssetsBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The assets_body of this AssetsBody.  # noqa: E501
        :rtype: AssetsBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def metadata(self) -> object:
        """Gets the metadata of this AssetsBody.


        :return: The metadata of this AssetsBody.
        :rtype: object
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: object):
        """Sets the metadata of this AssetsBody.


        :param metadata: The metadata of this AssetsBody.
        :type metadata: object
        """

        self._metadata = metadata

    @property
    def content(self) -> str:
        """Gets the content of this AssetsBody.


        :return: The content of this AssetsBody.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this AssetsBody.


        :param content: The content of this AssetsBody.
        :type content: str
        """

        self._content = content
