# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class OpeningHour(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, weekday: str=None, from_time: str=None, to_time: str=None):  # noqa: E501
        """OpeningHour - a model defined in Swagger

        :param weekday: The weekday of this OpeningHour.  # noqa: E501
        :type weekday: str
        :param from_time: The from_time of this OpeningHour.  # noqa: E501
        :type from_time: str
        :param to_time: The to_time of this OpeningHour.  # noqa: E501
        :type to_time: str
        """
        self.swagger_types = {
            'weekday': str,
            'from_time': str,
            'to_time': str
        }

        self.attribute_map = {
            'weekday': 'weekday',
            'from_time': 'fromTime',
            'to_time': 'toTime'
        }
        self._weekday = weekday
        self._from_time = from_time
        self._to_time = to_time

    @classmethod
    def from_dict(cls, dikt) -> 'OpeningHour':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpeningHour of this OpeningHour.  # noqa: E501
        :rtype: OpeningHour
        """
        return util.deserialize_model(dikt, cls)

    @property
    def weekday(self) -> str:
        """Gets the weekday of this OpeningHour.

        Single digit: 0=Mon, 1=Tue, ... 6=Sun)  # noqa: E501

        :return: The weekday of this OpeningHour.
        :rtype: str
        """
        return self._weekday

    @weekday.setter
    def weekday(self, weekday: str):
        """Sets the weekday of this OpeningHour.

        Single digit: 0=Mon, 1=Tue, ... 6=Sun)  # noqa: E501

        :param weekday: The weekday of this OpeningHour.
        :type weekday: str
        """
        allowed_values = ["0", "1", "2", "3", "4", "5", "6"]  # noqa: E501
        if weekday not in allowed_values:
            raise ValueError(
                "Invalid value for `weekday` ({0}), must be one of {1}"
                .format(weekday, allowed_values)
            )

        self._weekday = weekday

    @property
    def from_time(self) -> str:
        """Gets the from_time of this OpeningHour.


        :return: The from_time of this OpeningHour.
        :rtype: str
        """
        return self._from_time

    @from_time.setter
    def from_time(self, from_time: str):
        """Sets the from_time of this OpeningHour.


        :param from_time: The from_time of this OpeningHour.
        :type from_time: str
        """

        self._from_time = from_time

    @property
    def to_time(self) -> str:
        """Gets the to_time of this OpeningHour.


        :return: The to_time of this OpeningHour.
        :rtype: str
        """
        return self._to_time

    @to_time.setter
    def to_time(self, to_time: str):
        """Sets the to_time of this OpeningHour.


        :param to_time: The to_time of this OpeningHour.
        :type to_time: str
        """

        self._to_time = to_time
