# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PlayoutPlanTargetGroup(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, start_age: int=None, end_age: int=None, gender: str=None):  # noqa: E501
        """PlayoutPlanTargetGroup - a model defined in Swagger

        :param start_age: The start_age of this PlayoutPlanTargetGroup.  # noqa: E501
        :type start_age: int
        :param end_age: The end_age of this PlayoutPlanTargetGroup.  # noqa: E501
        :type end_age: int
        :param gender: The gender of this PlayoutPlanTargetGroup.  # noqa: E501
        :type gender: str
        """
        self.swagger_types = {
            'start_age': int,
            'end_age': int,
            'gender': str
        }

        self.attribute_map = {
            'start_age': 'startAge',
            'end_age': 'endAge',
            'gender': 'gender'
        }
        self._start_age = start_age
        self._end_age = end_age
        self._gender = gender

    @classmethod
    def from_dict(cls, dikt) -> 'PlayoutPlanTargetGroup':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlayoutPlan_targetGroup of this PlayoutPlanTargetGroup.  # noqa: E501
        :rtype: PlayoutPlanTargetGroup
        """
        return util.deserialize_model(dikt, cls)

    @property
    def start_age(self) -> int:
        """Gets the start_age of this PlayoutPlanTargetGroup.


        :return: The start_age of this PlayoutPlanTargetGroup.
        :rtype: int
        """
        return self._start_age

    @start_age.setter
    def start_age(self, start_age: int):
        """Sets the start_age of this PlayoutPlanTargetGroup.


        :param start_age: The start_age of this PlayoutPlanTargetGroup.
        :type start_age: int
        """

        self._start_age = start_age

    @property
    def end_age(self) -> int:
        """Gets the end_age of this PlayoutPlanTargetGroup.


        :return: The end_age of this PlayoutPlanTargetGroup.
        :rtype: int
        """
        return self._end_age

    @end_age.setter
    def end_age(self, end_age: int):
        """Sets the end_age of this PlayoutPlanTargetGroup.


        :param end_age: The end_age of this PlayoutPlanTargetGroup.
        :type end_age: int
        """

        self._end_age = end_age

    @property
    def gender(self) -> str:
        """Gets the gender of this PlayoutPlanTargetGroup.


        :return: The gender of this PlayoutPlanTargetGroup.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this PlayoutPlanTargetGroup.


        :param gender: The gender of this PlayoutPlanTargetGroup.
        :type gender: str
        """
        allowed_values = ["male", "female", "any"]  # noqa: E501
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"
                .format(gender, allowed_values)
            )

        self._gender = gender
