# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class SpecialDaysInner(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, _date: str=None, from_time: str=None, to_time: str=None):  # noqa: E501
        """SpecialDaysInner - a model defined in Swagger

        :param _date: The _date of this SpecialDaysInner.  # noqa: E501
        :type _date: str
        :param from_time: The from_time of this SpecialDaysInner.  # noqa: E501
        :type from_time: str
        :param to_time: The to_time of this SpecialDaysInner.  # noqa: E501
        :type to_time: str
        """
        self.swagger_types = {
            '_date': str,
            'from_time': str,
            'to_time': str
        }

        self.attribute_map = {
            '_date': 'date',
            'from_time': 'fromTime',
            'to_time': 'toTime'
        }
        self.__date = _date
        self._from_time = from_time
        self._to_time = to_time

    @classmethod
    def from_dict(cls, dikt) -> 'SpecialDaysInner':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SpecialDays_inner of this SpecialDaysInner.  # noqa: E501
        :rtype: SpecialDaysInner
        """
        return util.deserialize_model(dikt, cls)

    @property
    def _date(self) -> str:
        """Gets the _date of this SpecialDaysInner.


        :return: The _date of this SpecialDaysInner.
        :rtype: str
        """
        return self.__date

    @_date.setter
    def _date(self, _date: str):
        """Sets the _date of this SpecialDaysInner.


        :param _date: The _date of this SpecialDaysInner.
        :type _date: str
        """

        self.__date = _date

    @property
    def from_time(self) -> str:
        """Gets the from_time of this SpecialDaysInner.


        :return: The from_time of this SpecialDaysInner.
        :rtype: str
        """
        return self._from_time

    @from_time.setter
    def from_time(self, from_time: str):
        """Sets the from_time of this SpecialDaysInner.


        :param from_time: The from_time of this SpecialDaysInner.
        :type from_time: str
        """

        self._from_time = from_time

    @property
    def to_time(self) -> str:
        """Gets the to_time of this SpecialDaysInner.


        :return: The to_time of this SpecialDaysInner.
        :rtype: str
        """
        return self._to_time

    @to_time.setter
    def to_time(self, to_time: str):
        """Sets the to_time of this SpecialDaysInner.


        :param to_time: The to_time of this SpecialDaysInner.
        :type to_time: str
        """

        self._to_time = to_time
